package com.racloop.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName = "JourneyPair")
public class JourneyPair {
	
	private String id;
	private String initiatorJourneyId;
	private String recieverJourneyId;
	
	/**
	 * **** INITIATOR ************* RECIEVER ********** 
	 * 
	 * 		REQUESTED				PENDING
	 * 		ACCEPTED				ACCEPTED
	 * 		REJECTED				REJECTED
	 * 		CANCELLED_BY_OTHER		CANCELLED_BY_SELF
	 * 		CANCELLED_BY_SELF		CANCELLED_BY_OTHER
	 * 		FROZEN					FROZEN	// A -> B & A -> C => B -> C
	 */
	private String initiatorStatus; //REQUESTED, ACCEPTED, REJECTED, CANCELLED_BY_OTHER, CANCELLED_BY_SELF, FROZEN
	private String recieverStatus; //PENDING, ACCEPTED, REJECTED, CANCELLED_BY_OTHER, CANCELLED_BY_SELF, FROZEN
	/**
	 * A -> save & B -> save => both are appearing in search results
	 * C -> A & C -> B => AB ?? will they appear in search results and who will be initiator ??
	 * Use chronological order for initiator
	 */
	private String initiatorDirection; //INCOMING, OUTGOING, FORCED
	private String recieverDirection; //INCOMING, OUTGOING, FORCED
	private Long version;


	@Override 
	public String toString(){
		StringBuffer buffer = new StringBuffer();
		buffer.append("id : " + id + ", ");
		buffer.append("initiatorJourneyId : " + initiatorJourneyId + ", ");
		buffer.append("recieverJourneyId : " + recieverJourneyId + ", ");
		buffer.append("initiatorStatus : " + initiatorStatus + ", ");
		buffer.append("recieverStatus : " + recieverStatus + ", ");
		buffer.append("initiatorDirection : " + initiatorDirection + ", ");
		buffer.append("recieverDirection : " + recieverDirection + ", ");
		return buffer.toString();
	}
	
	@Override
	public int hashCode() {
		return id.hashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		JourneyPair other = (JourneyPair)obj;
		return other.id.equals(this.id);
	}
	
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public String getInitiatorJourneyId() {
		return initiatorJourneyId;
	}
	public void setInitiatorJourneyId(String initiatorJourneyId) {
		this.initiatorJourneyId = initiatorJourneyId;
	}
	
	public String getRecieverJourneyId() {
		return recieverJourneyId;
	}
	public void setRecieverJourneyId(String recieverJourneyId) {
		this.recieverJourneyId = recieverJourneyId;
	}
	
	public String getInitiatorStatus() {
		return initiatorStatus;
	}
	public void setInitiatorStatus(String initiatorStatus) {
		this.initiatorStatus = initiatorStatus;
	}
	
	public String getRecieverStatus() {
		return recieverStatus;
	}
	public void setRecieverStatus(String recieverStatus) {
		this.recieverStatus = recieverStatus;
	}
	
	public String getInitiatorDirection() {
		return initiatorDirection;
	}
	public void setInitiatorDirection(String initiatorDirection) {
		this.initiatorDirection = initiatorDirection;
	}
	
	public String getRecieverDirection() {
		return recieverDirection;
	}
	public void setRecieverDirection(String recieverDirection) {
		this.recieverDirection = recieverDirection;
	}
	
	@DynamoDBVersionAttribute
	public Long getVersion() {
		return version;
	}
	public void setVersion(Long version) {
		this.version = version;
	}

}
